### PR TITLE
First step in altering existing billa integration to work with shop.billa.cz

### PR DESCRIPTION
**Pull request by jhutar**
Ok. Bit naiive attempt to make shop.billa.cz work.

It is far more complicated than I though and although I do not see any error on `npm run dev`, I also do not see any data in UI :)

If anybody could help, that would be great.

### CODE REVIEW

**Comment by jhutar** [comment]
Hello @badlogic ! Sorry for pulling you into this. Initially I thought it will be enough to change URL of the shop, but looks like Billa in CZ uses slightly (?) different version.

Do you happen to know what might be the issue in this PR? When I run `npm run dev`, last think I see is `Copied latest items to site.`, but looks like I'm missing data in the UI.

**Comment by badlogic** [comment]
No worries @jhutar had a quick look at your fix1 branch.

First of all, it seems your integration only fetches ~200 products:
```
Fetched BILLA data, took 1.0755950421094895 seconds, 202/202 items without category.
```

The crawler uses categories to query products. You modified the original ones as they differ obviously, but there's only a single one in there:

```
exports.categories = [
    {
        name: "pecivo-1198",
    },
];
```

In any case, the data is correctly written to `site/output/data/`. For each store you'll get a `latest-canonical-<storename>.compressed.json`. That indeed has the info you want.

Screenshot 2023-09-19 at 20 38 35

The front end then fetches each store's latest canonical file. Which files are fetched (and thus which stores are exposed) is defined in `site/model/stores.js`. You have all stores enabled in there, so the front end tries to fetch all of them.

Screenshot 2023-09-19 at 20 40 23

It only succeeds fetching the Billa file, as expected, as that's the only file you generate via the crawler at the moment. The items also get loaded correctly based on the log output of the frontend:

Screenshot 2023-09-19 at 20 42 46

However, when searching for a product, the items-filter fails. That's because you left all the stores in there for which there aren't any latest canonical files. So, just remove all the stores for which you don't generate data in `site/model/stores.js`

Screenshot 2023-09-19 at 20 45 21

The next problem is that you ripped out all the categories in `site/model/categories`

Screenshot 2023-09-19 at 20 46 29

I'd leave categories as a task for some later date. For now, I suggest just commenting likes 308 to 322, which will basically disable categories in the UI all together.

Screenshot 2023-09-19 at 20 50 15

With these two changes (remove stores for which you don't generate data from `site/model/stores.js`, and comment the filter part in `items-filter.js`), you can happily search for products.

Screenshot 2023-09-19 at 20 51 47

**Comment by badlogic** [comment]
Btw, I strongly suggest to pull in this PR by @darkyenus https://github.com/badlogic/heissepreise/pull/149 that should make localization easier.

**Comment by jhutar** [comment]
This is great, thank you a lot for detailed guide! Works for me now.

BTW I only had one category to allow faster iteration for me, will add rest of them now.

**Comment by jhutar** [comment]
Hello @xsuchy . IMHO this is ready to be merged thanks to Mario.

Units needs to be fixed and categories functionality needs to be brought back, but at least import works now.

**Comment by xsuchy** [comment]
@jhutar It works nicely. I have already deployed. There is one glitch. The clicks on the products do not work (links to shop.billa.cz)

**Pull request merged**
